import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://biqjbazqrlgijsaqzqhe.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcWpiYXpxcmxnaWpzYXF6cWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzA5MjYsImV4cCI6MjA4NTk0NjkyNn0.KBhorhjRY0BPrE50vcTkSn7Ru2UK6OCmsb8qsNK3N5g'

const supabase = createClient(supabaseUrl, supabaseKey)

const propertyImages = [
    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2671&auto=format&fit=crop', // luxuryVilla1
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2670&auto=format&fit=crop', // luxuryVilla2
    'https://images.unsplash.com/photo-1600596542815-27b88e54e69b?q=80&w=2674&auto=format&fit=crop', // luxuryVilla3
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2653&auto=format&fit=crop', // luxuryVilla4
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=2670&auto=format&fit=crop', // luxuryVilla5
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=735&auto=format&fit=crop', // urbanLuxe
    'https://images.unsplash.com/photo-1588667822941-6e3c6319859f?q=80&w=500&auto=format&fit=crop', // golfCourse
    'https://images.unsplash.com/photo-1502444330042-d1a1ddf9bb5b?q=80&w=500&auto=format&fit=crop' // ranch
];

// Recreating data from Home.jsx
const newListed = Array.from({ length: 20 }).map((_, i) => ({
    // id: autogenerated by Supabase
    image: propertyImages[i % 5],
    price: 1200000 + i * 50000, // stored as number
    title: `Luxury Villa ${i + 1}`,
    location: 'Beverly Hills, CA',
    beds: 4 + (i % 3),
    baths: 3 + (i % 2),
    sqft: 2500 + i * 100,
    featured: i % 3 === 0,
    type: 'Villa', // Adding a type field just in case
    description: 'A beautiful luxury villa with modern amenities.'
}));

const nearbyProperties = Array.from({ length: 20 }).map((_, i) => ({
    // id: autogenerated
    image: propertyImages[(i + 2) % 5],
    price: 850000 + i * 25000, // stored as number
    title: `Modern Apartment ${i + 1}`,
    location: 'West Hollywood, CA',
    beds: 2 + (i % 2),
    baths: 2,
    sqft: 1200 + i * 50,
    // featured: undefined (false default?)
    type: 'Apartment',
    description: 'A modern apartment close to city center.'
}));

const allProperties = [...newListed, ...nearbyProperties];

async function seed() {
    console.log('Creating seeder user...');
    const email = `test_seeder_${Date.now()}@urbanplot.com`;
    const password = 'Password123!';

    const { data: authData, error: authError } = await supabase.auth.signUp({
        email,
        password,
        options: {
            data: {
                name: 'Seeder Bot'
            }
        }
    });

    if (authError) {
        console.error('Error creating seeder user:', authError);
        return;
    }

    const userId = authData.user.id;
    console.log(`Created seeder user: ${email} (${userId})`);

    // Wait a bit for trigger to create profile if needed
    await new Promise(resolve => setTimeout(resolve, 2000));

    console.log('Checking existing properties...');
    const { count, error: countError } = await supabase.from('properties').select('*', { count: 'exact', head: true });

    if (countError) {
        console.error('Error counting properties:', countError);
        return;
    }

    if (count > 0) {
        console.log(`Found ${count} existing properties. Skipping seed to avoid duplicates.`);
        return;
    }

    console.log(`Seeding ${allProperties.length} properties...`);

    const mappedProperties = allProperties.map(p => ({
        property_name: p.title,
        location: p.location,
        price: p.price,
        property_type: p.type,
        bedrooms: p.beds,
        bathrooms: p.baths,
        area_sqft: p.sqft,
        description: p.description,
        images: [p.image], // Store as JSON array
        user_id: userId,
        status: 'Available'
    }));

    // Insert in batches
    const { data, error } = await supabase
        .from('properties')
        .insert(mappedProperties)
        .select();

    if (error) {
        console.error('Error inserting properties:', error);
    } else {
        console.log(`Successfully inserted ${data.length} properties.`);
        if (data.length > 0) {
            console.log('First property ID:', data[0].id);
        }
    }
}

seed();
